import pandas as pd

# 参考《中国食物成分表》标准版，每100g可食部
# 评分规则：
# - 蛋白质：0-10分（0=无，10=优质蛋白含量高）
# - 膳食纤维：0-10分（0=无，10=极高）
# - 微量元素：0-10分（维生素、矿物质综合评分）
# - 添加糖：0-10分（0=无添加糖，10=含糖量极高）
# - 饱和脂肪：0-10分（0=无，10=极高）
# - 钠：0-10分（0=无，10=极高）

foods_data = [
    # ==================== 主食类 (20种) ====================
    {"name": "糙米饭", "category": "主食", "calories": 111, "protein": 4, "fiber": 6, "vitamins": 5, "sugar": 1, "saturated_fat": 1, "sodium": 1, "season": "四季", "tags": "粗粮,低GI"},
    {"name": "白米饭", "category": "主食", "calories": 130, "protein": 2, "fiber": 1, "vitamins": 2, "sugar": 0, "saturated_fat": 0, "sodium": 0, "season": "四季", "tags": "主食"},
    {"name": "燕麦", "category": "主食", "calories": 389, "protein": 8, "fiber": 10, "vitamins": 6, "sugar": 1, "saturated_fat": 2, "sodium": 2, "season": "四季", "tags": "膳食纤维,早餐"},
    {"name": "全麦面包", "category": "主食", "calories": 250, "protein": 6, "fiber": 7, "vitamins": 5, "sugar": 4, "saturated_fat": 1, "sodium": 4, "season": "四季", "tags": "早餐,低脂"},
    {"name": "红薯", "category": "主食", "calories": 86, "protein": 1, "fiber": 3, "vitamins": 7, "sugar": 4, "saturated_fat": 0, "sodium": 1, "season": "秋季", "tags": "粗粮,维生素A"},
    {"name": "紫薯", "category": "主食", "calories": 82, "protein": 2, "fiber": 4, "vitamins": 8, "sugar": 5, "saturated_fat": 0, "sodium": 1, "season": "秋季", "tags": "粗粮,花青素"},
    {"name": "玉米", "category": "主食", "calories": 112, "protein": 3, "fiber": 3, "vitamins": 6, "sugar": 6, "saturated_fat": 1, "sodium": 1, "season": "夏季", "tags": "粗粮,甜"},
    {"name": "小米", "category": "主食", "calories": 361, "protein": 5, "fiber": 3, "vitamins": 5, "sugar": 1, "saturated_fat": 1, "sodium": 1, "season": "四季", "tags": "粗粮,养胃"},
    {"name": "藜麦", "category": "主食", "calories": 368, "protein": 8, "fiber": 7, "vitamins": 7, "sugar": 1, "saturated_fat": 1, "sodium": 1, "season": "四季", "tags": "超级食物,高蛋白"},
    {"name": "荞麦面", "category": "主食", "calories": 340, "protein": 6, "fiber": 4, "vitamins": 5, "sugar": 1, "saturated_fat": 1, "sodium": 3, "season": "四季", "tags": "粗粮,低GI"},
    {"name": "意大利面", "category": "主食", "calories": 350, "protein": 5, "fiber": 2, "vitamins": 3, "sugar": 1, "saturated_fat": 1, "sodium": 1, "season": "四季", "tags": "主食"},
    {"name": "馒头", "category": "主食", "calories": 220, "protein": 4, "fiber": 1, "vitamins": 2, "sugar": 2, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "传统主食"},
    {"name": "包子（肉馅）", "category": "主食", "calories": 280, "protein": 7, "fiber": 1, "vitamins": 3, "sugar": 2, "saturated_fat": 4, "sodium": 4, "season": "四季", "tags": "传统小吃"},
    {"name": "饺子（猪肉白菜）", "category": "主食", "calories": 250, "protein": 6, "fiber": 1, "vitamins": 3, "sugar": 1, "saturated_fat": 3, "sodium": 4, "season": "冬季", "tags": "传统美食"},
    {"name": "馄饨", "category": "主食", "calories": 220, "protein": 5, "fiber": 1, "vitamins": 3, "sugar": 1, "saturated_fat": 2, "sodium": 5, "season": "四季", "tags": "小吃"},
    {"name": "炒饭", "category": "主食", "calories": 180, "protein": 4, "fiber": 1, "vitamins": 3, "sugar": 1, "saturated_fat": 3, "sodium": 4, "season": "四季", "tags": "家常菜"},
    {"name": "蛋炒饭", "category": "主食", "calories": 200, "protein": 5, "fiber": 1, "vitamins": 4, "sugar": 1, "saturated_fat": 4, "sodium": 4, "season": "四季", "tags": "家常菜"},
    {"name": "土豆泥", "category": "主食", "calories": 120, "protein": 2, "fiber": 2, "vitamins": 5, "sugar": 2, "saturated_fat": 2, "sodium": 2, "season": "四季", "tags": "西式"},
    {"name": "山药", "category": "主食", "calories": 56, "protein": 2, "fiber": 2, "vitamins": 6, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "秋季", "tags": "滋补,养胃"},
    {"name": "芋头", "category": "主食", "calories": 79, "protein": 2, "fiber": 2, "vitamins": 5, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "秋季", "tags": "粗粮"},
    
    # ==================== 蛋白质类 (35种) ====================
    {"name": "鸡胸肉", "category": "蛋白质", "calories": 165, "protein": 9, "fiber": 0, "vitamins": 5, "sugar": 0, "saturated_fat": 1, "sodium": 2, "season": "四季", "tags": "高蛋白,低脂"},
    {"name": "鸡腿肉", "category": "蛋白质", "calories": 200, "protein": 8, "fiber": 0, "vitamins": 5, "sugar": 0, "saturated_fat": 4, "sodium": 2, "season": "四季", "tags": "高蛋白"},
    {"name": "鸡翅", "category": "蛋白质", "calories": 220, "protein": 7, "fiber": 0, "vitamins": 4, "sugar": 0, "saturated_fat": 6, "sodium": 3, "season": "四季", "tags": ""},
    {"name": "鸭肉", "category": "蛋白质", "calories": 240, "protein": 7, "fiber": 0, "vitamins": 5, "sugar": 0, "saturated_fat": 7, "sodium": 4, "season": "秋季", "tags": "滋阴"},
    {"name": "三文鱼", "category": "蛋白质", "calories": 208, "protein": 8, "fiber": 0, "vitamins": 8, "sugar": 0, "saturated_fat": 3, "sodium": 3, "season": "四季", "tags": "Omega-3,深海鱼"},
    {"name": "鳕鱼", "category": "蛋白质", "calories": 82, "protein": 7, "fiber": 0, "vitamins": 6, "sugar": 0, "saturated_fat": 1, "sodium": 3, "season": "四季", "tags": "低脂,深海鱼"},
    {"name": "鲈鱼", "category": "蛋白质", "calories": 105, "protein": 8, "fiber": 0, "vitamins": 6, "sugar": 0, "saturated_fat": 2, "sodium": 3, "season": "四季", "tags": "淡水鱼"},
    {"name": "带鱼", "category": "蛋白质", "calories": 127, "protein": 7, "fiber": 0, "vitamins": 5, "sugar": 0, "saturated_fat": 3, "sodium": 4, "season": "四季", "tags": "海鱼"},
    {"name": "虾", "category": "蛋白质", "calories": 85, "protein": 9, "fiber": 0, "vitamins": 6, "sugar": 0, "saturated_fat": 1, "sodium": 4, "season": "四季", "tags": "高蛋白,低脂"},
    {"name": "蟹", "category": "蛋白质", "calories": 103, "protein": 8, "fiber": 0, "vitamins": 7, "sugar": 0, "saturated_fat": 1, "sodium": 5, "season": "秋季", "tags": "鲜美"},
    {"name": "扇贝", "category": "蛋白质", "calories": 88, "protein": 7, "fiber": 0, "vitamins": 6, "sugar": 0, "saturated_fat": 1, "sodium": 4, "season": "四季", "tags": "海鲜"},
    {"name": "牛肉", "category": "蛋白质", "calories": 250, "protein": 9, "fiber": 0, "vitamins": 6, "sugar": 0, "saturated_fat": 5, "sodium": 3, "season": "四季", "tags": "高蛋白,铁质"},
    {"name": "牛排", "category": "蛋白质", "calories": 280, "protein": 8, "fiber": 0, "vitamins": 6, "sugar": 0, "saturated_fat": 7, "sodium": 3, "season": "四季", "tags": "西餐"},
    {"name": "羊肉", "category": "蛋白质", "calories": 230, "protein": 7, "fiber": 0, "vitamins": 6, "sugar": 0, "saturated_fat": 6, "sodium": 4, "season": "冬季", "tags": "温补"},
    {"name": "猪肉（瘦）", "category": "蛋白质", "calories": 143, "protein": 8, "fiber": 0, "vitamins": 5, "sugar": 0, "saturated_fat": 2, "sodium": 2, "season": "四季", "tags": "瘦肉"},
    {"name": "五花肉", "category": "蛋白质", "calories": 350, "protein": 4, "fiber": 0, "vitamins": 4, "sugar": 0, "saturated_fat": 8, "sodium": 3, "season": "四季", "tags": "高脂肪"},
    {"name": "排骨", "category": "蛋白质", "calories": 280, "protein": 6, "fiber": 0, "vitamins": 5, "sugar": 0, "saturated_fat": 6, "sodium": 3, "season": "四季", "tags": ""},
    {"name": "火腿", "category": "蛋白质", "calories": 200, "protein": 6, "fiber": 0, "vitamins": 4, "sugar": 2, "saturated_fat": 4, "sodium": 8, "season": "四季", "tags": "加工肉"},
    {"name": "培根", "category": "蛋白质", "calories": 450, "protein": 5, "fiber": 0, "vitamins": 3, "sugar": 1, "saturated_fat": 8, "sodium": 9, "season": "四季", "tags": "加工肉"},
    {"name": "鸡蛋", "category": "蛋白质", "calories": 155, "protein": 8, "fiber": 0, "vitamins": 6, "sugar": 1, "saturated_fat": 3, "sodium": 2, "season": "四季", "tags": "优质蛋白"},
    {"name": "鸭蛋", "category": "蛋白质", "calories": 180, "protein": 7, "fiber": 0, "vitamins": 6, "sugar": 1, "saturated_fat": 4, "sodium": 3, "season": "四季", "tags": ""},
    {"name": "鹌鹑蛋", "category": "蛋白质", "calories": 160, "protein": 8, "fiber": 0, "vitamins": 6, "sugar": 1, "saturated_fat": 3, "sodium": 2, "season": "四季", "tags": ""},
    {"name": "豆腐", "category": "蛋白质", "calories": 76, "protein": 6, "fiber": 1, "vitamins": 5, "sugar": 1, "saturated_fat": 1, "sodium": 1, "season": "四季", "tags": "素食,低脂"},
    {"name": "豆腐干", "category": "蛋白质", "calories": 140, "protein": 7, "fiber": 1, "vitamins": 5, "sugar": 1, "saturated_fat": 2, "sodium": 4, "season": "四季", "tags": "素食"},
    {"name": "腐竹", "category": "蛋白质", "calories": 460, "protein": 8, "fiber": 1, "vitamins": 5, "sugar": 1, "saturated_fat": 4, "sodium": 2, "season": "四季", "tags": "素食"},
    {"name": "豆浆", "category": "蛋白质", "calories": 30, "protein": 4, "fiber": 1, "vitamins": 5, "sugar": 2, "saturated_fat": 1, "sodium": 1, "season": "四季", "tags": "植物蛋白"},
    {"name": "牛奶", "category": "蛋白质", "calories": 42, "protein": 5, "fiber": 0, "vitamins": 6, "sugar": 5, "saturated_fat": 2, "sodium": 2, "season": "四季", "tags": "钙质"},
    {"name": "酸奶", "category": "蛋白质", "calories": 60, "protein": 5, "fiber": 0, "vitamins": 6, "sugar": 6, "saturated_fat": 2, "sodium": 2, "season": "四季", "tags": "益生菌"},
    {"name": "奶酪", "category": "蛋白质", "calories": 320, "protein": 8, "fiber": 0, "vitamins": 6, "sugar": 1, "saturated_fat": 7, "sodium": 6, "season": "四季", "tags": "高钙"},
    {"name": "扁豆", "category": "蛋白质", "calories": 120, "protein": 5, "fiber": 4, "vitamins": 5, "sugar": 2, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "豆类"},
    {"name": "鹰嘴豆", "category": "蛋白质", "calories": 139, "protein": 5, "fiber": 4, "vitamins": 5, "sugar": 2, "saturated_fat": 1, "sodium": 1, "season": "四季", "tags": "超级食物"},
    {"name": "毛豆", "category": "蛋白质", "calories": 131, "protein": 6, "fiber": 4, "vitamins": 6, "sugar": 2, "saturated_fat": 1, "sodium": 1, "season": "夏季", "tags": "豆类"},
    
    # ==================== 蔬菜类 (50种) ====================
    {"name": "西兰花", "category": "蔬菜", "calories": 34, "protein": 4, "fiber": 4, "vitamins": 9, "sugar": 1, "saturated_fat": 0, "sodium": 2, "season": "四季", "tags": "高纤维,维生素C"},
    {"name": "菠菜", "category": "蔬菜", "calories": 23, "protein": 3, "fiber": 3, "vitamins": 8, "sugar": 1, "saturated_fat": 0, "sodium": 2, "season": "春季", "tags": "补铁,维生素K"},
    {"name": "羽衣甘蓝", "category": "蔬菜", "calories": 49, "protein": 4, "fiber": 4, "vitamins": 9, "sugar": 1, "saturated_fat": 0, "sodium": 2, "season": "四季", "tags": "超级蔬菜"},
    {"name": "生菜", "category": "蔬菜", "calories": 15, "protein": 1, "fiber": 1, "vitamins": 5, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "沙拉"},
    {"name": "白菜", "category": "蔬菜", "calories": 13, "protein": 1, "fiber": 1, "vitamins": 5, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "冬季", "tags": "家常"},
    {"name": "娃娃菜", "category": "蔬菜", "calories": 12, "protein": 1, "fiber": 1, "vitamins": 5, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": ""},
    {"name": "油菜", "category": "蔬菜", "calories": 15, "protein": 2, "fiber": 2, "vitamins": 6, "sugar": 1, "saturated_fat": 0, "sodium": 2, "season": "春季", "tags": "钙质"},
    {"name": "空心菜", "category": "蔬菜", "calories": 20, "protein": 2, "fiber": 2, "vitamins": 6, "sugar": 1, "saturated_fat": 0, "sodium": 2, "season": "夏季", "tags": ""},
    {"name": "茼蒿", "category": "蔬菜", "calories": 21, "protein": 2, "fiber": 2, "vitamins": 6, "sugar": 1, "saturated_fat": 0, "sodium": 2, "season": "冬季", "tags": ""},
    {"name": "芹菜", "category": "蔬菜", "calories": 14, "protein": 1, "fiber": 2, "vitamins": 5, "sugar": 1, "saturated_fat": 0, "sodium": 4, "season": "四季", "tags": "高纤维"},
    {"name": "西红柿", "category": "蔬菜", "calories": 18, "protein": 1, "fiber": 2, "vitamins": 7, "sugar": 3, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "维生素C"},
    {"name": "黄瓜", "category": "蔬菜", "calories": 15, "protein": 1, "fiber": 1, "vitamins": 4, "sugar": 2, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "低卡,补水"},
    {"name": "冬瓜", "category": "蔬菜", "calories": 11, "protein": 0, "fiber": 1, "vitamins": 4, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "低卡"},
    {"name": "南瓜", "category": "蔬菜", "calories": 26, "protein": 1, "fiber": 1, "vitamins": 6, "sugar": 3, "saturated_fat": 0, "sodium": 1, "season": "秋季", "tags": "维生素A"},
    {"name": "西葫芦", "category": "蔬菜", "calories": 17, "protein": 1, "fiber": 1, "vitamins": 5, "sugar": 2, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "低卡"},
    {"name": "茄子", "category": "蔬菜", "calories": 25, "protein": 1, "fiber": 2, "vitamins": 4, "sugar": 2, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": ""},
    {"name": "青椒", "category": "蔬菜", "calories": 22, "protein": 1, "fiber": 2, "vitamins": 7, "sugar": 2, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "维生素C"},
    {"name": "彩椒", "category": "蔬菜", "calories": 26, "protein": 1, "fiber": 2, "vitamins": 8, "sugar": 3, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "维生素C"},
    {"name": "洋葱", "category": "蔬菜", "calories": 40, "protein": 1, "fiber": 2, "vitamins": 5, "sugar": 4, "saturated_fat": 0, "sodium": 2, "season": "四季", "tags": "抗氧化"},
    {"name": "蒜", "category": "蔬菜", "calories": 149, "protein": 2, "fiber": 1, "vitamins": 5, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "调味"},
    {"name": "姜", "category": "蔬菜", "calories": 80, "protein": 1, "fiber": 1, "vitamins": 4, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "调味"},
    {"name": "胡萝卜", "category": "蔬菜", "calories": 41, "protein": 1, "fiber": 3, "vitamins": 9, "sugar": 5, "saturated_fat": 0, "sodium": 2, "season": "四季", "tags": "维生素A"},
    {"name": "白萝卜", "category": "蔬菜", "calories": 16, "protein": 1, "fiber": 2, "vitamins": 5, "sugar": 2, "saturated_fat": 0, "sodium": 2, "season": "冬季", "tags": "消食"},
    {"name": "莲藕", "category": "蔬菜", "calories": 74, "protein": 2, "fiber": 3, "vitamins": 5, "sugar": 2, "saturated_fat": 0, "sodium": 2, "season": "秋季", "tags": "滋补"},
    {"name": "山药", "category": "蔬菜", "calories": 56, "protein": 2, "fiber": 2, "vitamins": 6, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "秋季", "tags": "养胃"},
    {"name": "芦笋", "category": "蔬菜", "calories": 20, "protein": 2, "fiber": 2, "vitamins": 7, "sugar": 2, "saturated_fat": 0, "sodium": 1, "season": "春季", "tags": ""},
    {"name": "秋葵", "category": "蔬菜", "calories": 33, "protein": 2, "fiber": 3, "vitamins": 6, "sugar": 2, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": ""},
    {"name": "苦瓜", "category": "蔬菜", "calories": 17, "protein": 1, "fiber": 2, "vitamins": 5, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "清热"},
    {"name": "丝瓜", "category": "蔬菜", "calories": 20, "protein": 1, "fiber": 1, "vitamins": 5, "sugar": 2, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": ""},
    {"name": "蘑菇", "category": "蔬菜", "calories": 22, "protein": 3, "fiber": 1, "vitamins": 6, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "菌类,抗氧化"},
    {"name": "香菇", "category": "蔬菜", "calories": 26, "protein": 3, "fiber": 2, "vitamins": 6, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "菌类"},
    {"name": "金针菇", "category": "蔬菜", "calories": 32, "protein": 3, "fiber": 3, "vitamins": 5, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "菌类"},
    {"name": "杏鲍菇", "category": "蔬菜", "calories": 35, "protein": 3, "fiber": 2, "vitamins": 5, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "菌类"},
    {"name": "木耳", "category": "蔬菜", "calories": 25, "protein": 1, "fiber": 3, "vitamins": 5, "sugar": 1, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "菌类,胶质"},
    {"name": "海带", "category": "蔬菜", "calories": 43, "protein": 1, "fiber": 2, "vitamins": 5, "sugar": 0, "saturated_fat": 0, "sodium": 8, "season": "四季", "tags": "海藻,碘"},
    {"name": "紫菜", "category": "蔬菜", "calories": 35, "protein": 3, "fiber": 3, "vitamins": 6, "sugar": 0, "saturated_fat": 0, "sodium": 5, "season": "四季", "tags": "海藻,碘"},
    
    # ==================== 水果类 (30种) ====================
    {"name": "苹果", "category": "水果", "calories": 52, "protein": 0, "fiber": 2, "vitamins": 5, "sugar": 10, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "健康,膳食纤维"},
    {"name": "香蕉", "category": "水果", "calories": 89, "protein": 1, "fiber": 2, "vitamins": 6, "sugar": 12, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "高钾,能量"},
    {"name": "橙子", "category": "水果", "calories": 47, "protein": 1, "fiber": 2, "vitamins": 8, "sugar": 9, "saturated_fat": 0, "sodium": 1, "season": "冬季", "tags": "维生素C"},
    {"name": "橘子", "category": "水果", "calories": 44, "protein": 1, "fiber": 2, "vitamins": 7, "sugar": 9, "saturated_fat": 0, "sodium": 1, "season": "冬季", "tags": "维生素C"},
    {"name": "柚子", "category": "水果", "calories": 38, "protein": 1, "fiber": 1, "vitamins": 7, "sugar": 8, "saturated_fat": 0, "sodium": 1, "season": "秋季", "tags": "维生素C"},
    {"name": "柠檬", "category": "水果", "calories": 29, "protein": 1, "fiber": 1, "vitamins": 7, "sugar": 2, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "维生素C"},
    {"name": "蓝莓", "category": "水果", "calories": 57, "protein": 1, "fiber": 3, "vitamins": 7, "sugar": 10, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "抗氧化"},
    {"name": "草莓", "category": "水果", "calories": 32, "protein": 1, "fiber": 2, "vitamins": 9, "sugar": 5, "saturated_fat": 0, "sodium": 1, "season": "春季", "tags": "维生素C"},
    {"name": "猕猴桃", "category": "水果", "calories": 61, "protein": 1, "fiber": 3, "vitamins": 9, "sugar": 9, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "维生素C"},
    {"name": "葡萄", "category": "水果", "calories": 69, "protein": 1, "fiber": 1, "vitamins": 5, "sugar": 16, "saturated_fat": 0, "sodium": 1, "season": "秋季", "tags": "抗氧化"},
    {"name": "西瓜", "category": "水果", "calories": 30, "protein": 1, "fiber": 0, "vitamins": 6, "sugar": 6, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "补水"},
    {"name": "哈密瓜", "category": "水果", "calories": 34, "protein": 1, "fiber": 1, "vitamins": 6, "sugar": 8, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": ""},
    {"name": "桃子", "category": "水果", "calories": 39, "protein": 1, "fiber": 1, "vitamins": 5, "sugar": 8, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": ""},
    {"name": "梨", "category": "水果", "calories": 42, "protein": 0, "fiber": 2, "vitamins": 4, "sugar": 10, "saturated_fat": 0, "sodium": 1, "season": "秋季", "tags": "润肺"},
    {"name": "芒果", "category": "水果", "calories": 60, "protein": 1, "fiber": 2, "vitamins": 7, "sugar": 14, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "维生素A"},
    {"name": "菠萝", "category": "水果", "calories": 50, "protein": 1, "fiber": 1, "vitamins": 6, "sugar": 10, "saturated_fat": 0, "sodium": 1, "season": "春季", "tags": "蛋白酶"},
    {"name": "樱桃", "category": "水果", "calories": 50, "protein": 1, "fiber": 1, "vitamins": 6, "sugar": 12, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "抗氧化"},
    {"name": "石榴", "category": "水果", "calories": 83, "protein": 1, "fiber": 4, "vitamins": 6, "sugar": 13, "saturated_fat": 0, "sodium": 1, "season": "秋季", "tags": "抗氧化"},
    {"name": "柿子", "category": "水果", "calories": 70, "protein": 1, "fiber": 3, "vitamins": 7, "sugar": 12, "saturated_fat": 0, "sodium": 1, "season": "秋季", "tags": "维生素A"},
    {"name": "火龙果", "category": "水果", "calories": 55, "protein": 1, "fiber": 2, "vitamins": 4, "sugar": 8, "saturated_fat": 0, "sodium": 1, "season": "四季", "tags": "膳食纤维"},
    {"name": "百香果", "category": "水果", "calories": 97, "protein": 2, "fiber": 5, "vitamins": 7, "sugar": 11, "saturated_fat": 0, "sodium": 1, "season": "夏季", "tags": "维生素C"},
    {"name": "榴莲", "category": "水果", "calories": 147, "protein": 2, "fiber": 3, "vitamins": 5, "sugar": 13, "saturated_fat": 4, "sodium": 1, "season": "夏季", "tags": "高热量"},
    {"name": "牛油果", "category": "水果", "calories": 160, "protein": 2, "fiber": 7, "vitamins": 6, "sugar": 1, "saturated_fat": 4, "sodium": 1, "season": "四季", "tags": "健康脂肪"},
    
    # ==================== 家常菜 (60种) ====================
    {"name": "番茄炒蛋", "category": "家常菜", "calories": 98, "protein": 6, "fiber": 1, "vitamins": 7, "sugar": 4, "saturated_fat": 3, "sodium": 3, "season": "四季", "tags": "经典家常"},
    {"name": "青椒肉丝", "category": "家常菜", "calories": 150, "protein": 7, "fiber": 1, "vitamins": 6, "sugar": 2, "saturated_fat": 4, "sodium": 4, "season": "四季", "tags": "下饭菜"},
    {"name": "鱼香肉丝", "category": "家常菜", "calories": 180, "protein": 6, "fiber": 1, "vitamins": 5, "sugar": 6, "saturated_fat": 4, "sodium": 5, "season": "四季", "tags": "川菜"},
    {"name": "宫保鸡丁", "category": "家常菜", "calories": 170, "protein": 7, "fiber": 1, "vitamins": 5, "sugar": 5, "saturated_fat": 4, "sodium": 5, "season": "四季", "tags": "川菜"},
    {"name": "麻婆豆腐", "category": "家常菜", "calories": 120, "protein": 5, "fiber": 1, "vitamins": 5, "sugar": 2, "saturated_fat": 3, "sodium": 6, "season": "四季", "tags": "川菜"},
    {"name": "回锅肉", "category": "家常菜", "calories": 300, "protein": 5, "fiber": 0, "vitamins": 4, "sugar": 2, "saturated_fat": 7, "sodium": 5, "season": "四季", "tags": "川菜"},
    {"name": "红烧肉", "category": "家常菜", "calories": 350, "protein": 5, "fiber": 0, "vitamins": 4, "sugar": 5, "saturated_fat": 8, "sodium": 5, "season": "四季", "tags": "经典"},
    {"name": "糖醋排骨", "category": "家常菜", "calories": 280, "protein": 6, "fiber": 0, "vitamins": 4, "sugar": 8, "saturated_fat": 6, "sodium": 4, "season": "四季", "tags": "酸甜"},
    {"name": "可乐鸡翅", "category": "家常菜", "calories": 250, "protein": 6, "fiber": 0, "vitamins": 4, "sugar": 7, "saturated_fat": 5, "sodium": 4, "season": "四季", "tags": ""},
    {"name": "清蒸鲈鱼", "category": "家常菜", "calories": 110, "protein": 8, "fiber": 0, "vitamins": 6, "sugar": 1, "saturated_fat": 2, "sodium": 3, "season": "四季", "tags": "清淡"},
    {"name": "酸菜鱼", "category": "家常菜", "calories": 130, "protein": 7, "fiber": 1, "vitamins": 5, "sugar": 1, "saturated_fat": 3, "sodium": 7, "season": "四季", "tags": "川菜"},
    {"name": "水煮鱼", "category": "家常菜", "calories": 180, "protein": 7, "fiber": 1, "vitamins": 5, "sugar": 1, "saturated_fat": 5, "sodium": 7, "season": "四季", "tags": "川菜"},
    {"name": "干锅花菜", "category": "家常菜", "calories": 90, "protein": 3, "fiber": 2, "vitamins": 6, "sugar": 2, "saturated_fat": 3, "sodium": 5, "season": "四季", "tags": "香辣"},
    {"name": "地三鲜", "category": "家常菜", "calories": 140, "protein": 2, "fiber": 2, "vitamins": 5, "sugar": 3, "saturated_fat": 4, "sodium": 4, "season": "夏季", "tags": "东北菜"},
    {"name": "酸辣土豆丝", "category": "家常菜", "calories": 120, "protein": 2, "fiber": 2, "vitamins": 5, "sugar": 2, "saturated_fat": 2, "sodium": 4, "season": "四季", "tags": "下饭菜"},
    {"name": "醋溜白菜", "category": "家常菜", "calories": 60, "protein": 1, "fiber": 1, "vitamins": 5, "sugar": 2, "saturated_fat": 1, "sodium": 3, "season": "冬季", "tags": "清淡"},
    {"name": "蒜蓉西兰花", "category": "家常菜", "calories": 55, "protein": 4, "fiber": 4, "vitamins": 8, "sugar": 1, "saturated_fat": 1, "sodium": 3, "season": "四季", "tags": "健康"},
    {"name": "蚝油生菜", "category": "家常菜", "calories": 40, "protein": 1, "fiber": 1, "vitamins": 5, "sugar": 2, "saturated_fat": 1, "sodium": 5, "season": "四季", "tags": "快手菜"},
    {"name": "手撕包菜", "category": "家常菜", "calories": 70, "protein": 2, "fiber": 2, "vitamins": 6, "sugar": 2, "saturated_fat": 2, "sodium": 4, "season": "四季", "tags": "湘菜"},
    {"name": "干煸四季豆", "category": "家常菜", "calories": 110, "protein": 2, "fiber": 2, "vitamins": 5, "sugar": 2, "saturated_fat": 3, "sodium": 5, "season": "夏季", "tags": "川菜"},
    {"name": "虎皮青椒", "category": "家常菜", "calories": 80, "protein": 1, "fiber": 2, "vitamins": 7, "sugar": 3, "saturated_fat": 2, "sodium": 4, "season": "夏季", "tags": "下饭菜"},
    {"name": "红烧茄子", "category": "家常菜", "calories": 130, "protein": 1, "fiber": 2, "vitamins": 4, "sugar": 3, "saturated_fat": 4, "sodium": 4, "season": "夏季", "tags": ""},
    {"name": "鱼香茄子", "category": "家常菜", "calories": 150, "protein": 1, "fiber": 2, "vitamins": 4, "sugar": 5, "saturated_fat": 4, "sodium": 5, "season": "夏季", "tags": "川菜"},
    {"name": "西红柿炒鸡蛋", "category": "家常菜", "calories": 95, "protein": 5, "fiber": 1, "vitamins": 7, "sugar": 4, "saturated_fat": 2, "sodium": 2, "season": "四季", "tags": "国民菜"},
    {"name": "韭菜炒鸡蛋", "category": "家常菜", "calories": 110, "protein": 6, "fiber": 1, "vitamins": 6, "sugar": 1, "saturated_fat": 3, "sodium": 2, "season": "春季", "tags": ""},
    {"name": "香干炒肉", "category": "家常菜", "calories": 160, "protein": 7, "fiber": 1, "vitamins": 5, "sugar": 2, "saturated_fat": 4, "sodium": 5, "season": "四季", "tags": ""},
    {"name": "蒜苔炒肉", "category": "家常菜", "calories": 140, "protein": 6, "fiber": 2, "vitamins": 5, "sugar": 2, "saturated_fat": 3, "sodium": 4, "season": "春季", "tags": ""},
    {"name": "荷兰豆炒腊肉", "category": "家常菜", "calories": 170, "protein": 5, "fiber": 2, "vitamins": 5, "sugar": 2, "saturated_fat": 5, "sodium": 6, "season": "冬季", "tags": ""},
    {"name": "红烧排骨", "category": "家常菜", "calories": 280, "protein": 7, "fiber": 0, "vitamins": 4, "sugar": 5, "saturated_fat": 7, "sodium": 5, "season": "四季", "tags": "经典"},
    {"name": "糖醋里脊", "category": "家常菜", "calories": 260, "protein": 6, "fiber": 0, "vitamins": 4, "sugar": 7, "saturated_fat": 5, "sodium": 4, "season": "四季", "tags": "酸甜"},
    {"name": "京酱肉丝", "category": "家常菜", "calories": 190, "protein": 7, "fiber": 0, "vitamins": 4, "sugar": 5, "saturated_fat": 4, "sodium": 6, "season": "四季", "tags": "北京菜"},
    {"name": "木须肉", "category": "家常菜", "calories": 150, "protein": 7, "fiber": 1, "vitamins": 5, "sugar": 2, "saturated_fat": 4, "sodium": 4, "season": "四季", "tags": ""},
    {"name": "宫保虾球", "category": "家常菜", "calories": 140, "protein": 8, "fiber": 0, "vitamins": 5, "sugar": 4, "saturated_fat": 3, "sodium": 4, "season": "四季", "tags": "川菜"},
    {"name": "椒盐虾", "category": "家常菜", "calories": 150, "protein": 8, "fiber": 0, "vitamins": 5, "sugar": 1, "saturated_fat": 3, "sodium": 5, "season": "四季", "tags": ""},
    {"name": "葱爆羊肉", "category": "家常菜", "calories": 200, "protein": 7, "fiber": 0, "vitamins": 5, "sugar": 1, "saturated_fat": 5, "sodium": 4, "season": "冬季", "tags": "温补"},
    {"name": "孜然牛肉", "category": "家常菜", "calories": 210, "protein": 7, "fiber": 0, "vitamins": 5, "sugar": 1, "saturated_fat": 5, "sodium": 5, "season": "四季", "tags": "烧烤风味"},
    {"name": "黑椒牛柳", "category": "家常菜", "calories": 190, "protein": 7, "fiber": 0, "vitamins": 5, "sugar": 2, "saturated_fat": 4, "sodium": 4, "season": "四季", "tags": "西式"},
    {"name": "西红柿牛腩", "category": "家常菜", "calories": 170, "protein": 7, "fiber": 1, "vitamins": 7, "sugar": 4, "saturated_fat": 4, "sodium": 4, "season": "四季", "tags": "经典"},
    {"name": "咖喱鸡肉", "category": "家常菜", "calories": 180, "protein": 7, "fiber": 1, "vitamins": 5, "sugar": 3, "saturated_fat": 4, "sodium": 5, "season": "四季", "tags": "东南亚"},
    {"name": "黄焖鸡", "category": "家常菜", "calories": 190, "protein": 8, "fiber": 1, "vitamins": 5, "sugar": 3, "saturated_fat": 4, "sodium": 5, "season": "四季", "tags": "鲁菜"},
    {"name": "大盘鸡", "category": "家常菜", "calories": 220, "protein": 7, "fiber": 1, "vitamins": 5, "sugar": 3, "saturated_fat": 4, "sodium": 5, "season": "四季", "tags": "新疆菜"},
    {"name": "辣子鸡", "category": "家常菜", "calories": 210, "protein": 7, "fiber": 0, "vitamins": 4, "sugar": 1, "saturated_fat": 5, "sodium": 6, "season": "四季", "tags": "川菜"},
    {"name": "毛血旺", "category": "家常菜", "calories": 240, "protein": 6, "fiber": 1, "vitamins": 5, "sugar": 2, "saturated_fat": 6, "sodium": 8, "season": "四季", "tags": "川菜"},
    {"name": "水煮肉片", "category": "家常菜", "calories": 200, "protein": 7, "fiber": 1, "vitamins": 5, "sugar": 1, "saturated_fat": 5, "sodium": 7, "season": "四季", "tags": "川菜"},
    {"name": "夫妻肺片", "category": "家常菜", "calories": 180, "protein": 6, "fiber": 0, "vitamins": 4, "sugar": 1, "saturated_fat": 5, "sodium": 7, "season": "四季", "tags": "川菜凉菜"},
    {"name": "口水鸡", "category": "家常菜", "calories": 160, "protein": 7, "fiber": 0, "vitamins": 4, "sugar": 1, "saturated_fat": 4, "sodium": 5, "season": "四季", "tags": "川菜凉菜"},
    {"name": "蒜泥白肉", "category": "家常菜", "calories": 220, "protein": 6, "fiber": 0, "vitamins": 4, "sugar": 1, "saturated_fat": 6, "sodium": 4, "season": "四季", "tags": "川菜凉菜"},
    {"name": "凉拌黄瓜", "category": "家常菜", "calories": 30, "protein": 1, "fiber": 1, "vitamins": 4, "sugar": 2, "saturated_fat": 0, "sodium": 4, "season": "夏季", "tags": "凉菜"},
    {"name": "拍黄瓜", "category": "家常菜", "calories": 35, "protein": 1, "fiber": 1, "vitamins": 4, "sugar": 2, "saturated_fat": 0, "sodium": 4, "season": "夏季", "tags": "凉菜"},
    {"name": "凉拌木耳", "category": "家常菜", "calories": 40, "protein": 1, "fiber": 2, "vitamins": 5, "sugar": 1, "saturated_fat": 0, "sodium": 4, "season": "四季", "tags": "凉菜"},
    {"name": "皮蛋豆腐", "category": "家常菜", "calories": 80, "protein": 4, "fiber": 0, "vitamins": 4, "sugar": 1, "saturated_fat": 2, "sodium": 5, "season": "夏季", "tags": "凉菜"},
    {"name": "大拌菜", "category": "家常菜", "calories": 50, "protein": 2, "fiber": 2, "vitamins": 6, "sugar": 2, "saturated_fat": 0, "sodium": 3, "season": "四季", "tags": "沙拉"},
    {"name": "酸辣汤", "category": "汤类", "calories": 60, "protein": 3, "fiber": 1, "vitamins": 4, "sugar": 2, "saturated_fat": 1, "sodium": 6, "season": "四季", "tags": "开胃"},
    {"name": "紫菜蛋花汤", "category": "汤类", "calories": 30, "protein": 3, "fiber": 1, "vitamins": 5, "sugar": 1, "saturated_fat": 1, "sodium": 4, "season": "四季", "tags": "快手汤"},
    {"name": "番茄蛋花汤", "category": "汤类", "calories": 35, "protein": 3, "fiber": 1, "vitamins": 6, "sugar": 2, "saturated_fat": 1, "sodium": 3, "season": "四季", "tags": ""},
    {"name": "冬瓜排骨汤", "category": "汤类", "calories": 90, "protein": 5, "fiber": 1, "vitamins": 4, "sugar": 1, "saturated_fat": 2, "sodium": 3, "season": "夏季", "tags": "清热"},
    {"name": "玉米排骨汤", "category": "汤类", "calories": 110, "protein": 5, "fiber": 1, "vitamins": 4, "sugar": 3, "saturated_fat": 2, "sodium": 3, "season": "四季", "tags": ""},
    {"name": "罗宋汤", "category": "汤类", "calories": 80, "protein": 3, "fiber": 2, "vitamins": 6, "sugar": 4, "saturated_fat": 1, "sodium": 5, "season": "四季", "tags": "西式"},
]

# 转换为 DataFrame
df = pd.DataFrame(foods_data)

# 保存为 CSV
df.to_csv('foods_200.csv', index=False, encoding='utf-8')
print(f"✅ 已生成 {len(foods_data)} 条食物数据，保存到 foods_200.csv")